function chnageparagraph() {
    document.getElementById('a1').innerText = "This is Useless paragraph.";
    document.getElementById('a').innerText = "This is Event Handling Website.";
    document.getElementById('a').style.color="red";
    document.getElementById('a').style.backgroundColor= 'yellow';
   // document.getElementById('b').style.backgroundColor='green';
}

function mouseover()
{
    document.getElementById('a').innerText="!!!!"
    document.getElementById('a1').innerText="This is my paragraph"
}
function margin() {
    document.getElementById('a1').style.fontSize='20px';
    document.getElementById('a1').style.fontFamily='Arial';
    document.getElementById('a1').style.margin= '50px'
    document.getElementById('a1').style.align= 'center'
}
function buton()
{
    document.getElementById('b').style.backgroundColor='green';
}
