// let a=prompt("Enter a number: ")
// a=parseInt(a)
// if (a%2==0) 
// {
//     document.write(a," is even Number ");
// }
// else 
// {
//     document.write(a," is odd Number");
// }

// for (let i = 0; i < 10; i++) 
// {
//     document.write("Ashfak Alam <br>")
// }

// alert("A > 50 and B < 50");
// let a=prompt("Enter a number: ");
// let b=prompt("Enter another number: ");
// a=parseInt(a);
// b=parseInt(b);
// if (a>50 && b<50) 
// {
//     document.write("A + b = ",a+b);
// }
// else{
//     document.write("Invalid Formet")
// }

// let a=prompt("Enter A: ");
// let b=prompt("Enter B: ");
// a=parseInt(a);
// b=parseInt(b);
// document.write("Average : ",(a+b)/2);

